enum MembershipActionTypeEnum {
  MEMBERSHIP_PLANS_LOADING = "MEMBERSHIP_PLANS_LOADING",
  MEMBERSHIP_PLANS_LOADED = "MEMBERSHIP_PLANS_LOADED",
  GET_MEMBERSHIP_PLANS = "GET_MEMBERSHIP_PLANS",
  EDIT_MEMBERSHIP_PLANS = "EDIT_MEMBERSHIP_PLANS",
  GET_MEMBERSHIP_PLANS_BY_ID = "GET_MEMBERSHIP_PLANS_BY_ID",
  GET_PLAN_ID = "GET_PLAN_ID",
  EDIT_FUEL_MEMBERSHIP_STATUS = "EDIT_FUEL_MEMBERSHIP_STATUS",
  EDIT_TANK_MEMBERSHIP_STATUS = "EDIT_TANK_MEMBERSHIP_STATUS",
}

export default MembershipActionTypeEnum;
