enum DashboardActionTypeEnum {
  DASHBOARD_LOADING = "DASHBOARD_LOADING",
  DASHBOARD_LOADED = "DASHBOARD_LOADED",
  GET_DASHBOARD_VIEW_DATA = "GET_DASHBOARD_VIEW_DATA",
  GET_DASHBOARD_ORDERS = "GET_DASHBOARD_ORDERS",
  GET_DASHBOARD_ALL_ORDERS = "GET_DASHBOARD_ALL_ORDERS",
}

export default DashboardActionTypeEnum;
