enum TransactionActionTypeEnum {
  TRANSACTION_LOADING = "TRANSACTION_LOADING",
  TRANSACTION_LOADED = "TRANSACTION_LOADED",
  GET_TRANSACTION = "GET_TRANSACTION",
  EDIT_TRANSACTION = "EDIT_TRANSACTION",
}

export default TransactionActionTypeEnum;
