enum actionTypes {
  GET_DELIVERY_LOCATION_PENDING = "GET_DELIVERY_LOCATION_PENDING",
  GET_DELIVERY_LOCATION_SUCCESS = "GET_DELIVERY_LOCATION_SUCCESS",
  GET_DELIVERY_LOCATION_FAILED = "GET_DELIVERY_LOCATION_FAILED",

  UPDATE_DELIVERY_LOCATION_PENDING = "UPDATE_DELIVERY_LOCATION_PENDING",
  UPDATE_DELIVERY_LOCATION_SUCCESS = "UPDATE_DELIVERY_LOCATION_SUCCESS ",
  UPDATE_DELIVERY_LOCATION_FAILED = "UPDATE_DELIVERY_LOCATION_FAILED",
}
export default actionTypes;
