enum RolesandPermissionTypeEnum {
  GET_ROLES_PENDING = "GET_ROLES_PENDING",
  GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS",
  GET_ROLES_FAILED = "GET_ROLES_FAILED",

  GET_ROLES_BY_ID_PENDING = "GET_ROLES_BY_ID_PENDING",
  GET_ROLES_BY_ID_SUCCESS = "GET_ROLES_BY_ID_SUCCESS",
  GET_ROLES_BY_ID_FAILED = "GET_ROLES_BY_ID_FAILED",

  GET_MODULES_PENDING = "GET_MODULES_PENDING",
  GET_MODULES_SUCCESS = "GET_MODULES_SUCCESS",
  GET_MODULES_FAILED = "GET_MODULES_FAILED",

  ADD_ROLES_PENDING = "ADD_ROLES_PENDING",
  ADD_ROLES_SUCCESS = "ADD_ROLES_SUCCESS",
  ADD_ROLES_FAILED = "ADD_ROLES_FAILED",

  UPDATE_ROLES_AND_PERMISSION_PENDING = "UPDATE_ROLES_AND_PERMISSION_PENDING",
  UPDATE_ROLES_AND_PERMISSION_SUCCESS = "UPDATE_ROLES_AND_PERMISSION_SUCCESS",
  UPDATE_ROLES_AND_PERMISSION_FAILED = "UPDATE_ROLES_AND_PERMISSION_FAILED",

  DELETE_ROLES_PENDING = "DELETE_ROLES_PENDING",
  DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS",
  DELETE_ROLES_FAILED = "DELETE_ROLES_FAILED",

  UPDATE_ROLES_STATUS_PENDING = "UPDATE_ROLES_STATUS_PENDING",
  UPDATE_ROLES_STATUS_SUCCESS = "UPDATE_ROLES_STATUS_SUCCESS",
  UPDATE_ROLES_STATUS_FAILED = "UPDATE_ROLES_STATUS_FAILED",
}
export default RolesandPermissionTypeEnum;
