enum MembershipActionTypeEnum {
  MEMBERSHIP_LOADING = "MEMBERSHIP_LOADING",
  MEMBERSHIP_LOADED = "MEMBERSHIP_LOADED",
  GET_MEMBERSHIP = "GET_MEMBERSHIP",
  EDIT_MEMBERSHIP = "EDIT_MEMBERSHIP",
  DELETE_MEMBERSHIP = "DELETE_MEMBERSHIP",
}

export default MembershipActionTypeEnum;
