enum AppSettingsActionTypeEnum {
  APP_SETTING_PENDING = "APP_SETTING_PENDING",
  APP_SETTING_LOADED = "APP_SETTING_LOADED",
  GET_APP_SETTING = "GET_APP_SETTING",
  UPDATE_APP_SETTING = "UPDATE_APP_SETTING",
}

export default AppSettingsActionTypeEnum;
