enum DriversActionTypeEnum {
  DRIVERS_LOADING = "DRIVERS_LOADING",
  DRIVERS_LOADED = "DRIVERS_LOADED",
  GET_VENDOR_DRIVERS = "GET_VENDOR_DRIVERS",
  GET_FREELANCE_DRIVERS = "GET_FREELANCE_DRIVERS",
  GET_FREELANCE_DRIVERS_PAYMENT = "GET_FREELANCE_DRIVERS_PAYMENT",
  GET_DRIVER_ORDERS = " GET_DRIVER_ORDERS",
  GET_DRIVER_COMPLETED_ORDERS = "GET_DRIVER_COMPLETED_ORDERS",
  GET_ALL_DRIVERS = "GET_ALL_DRIVERS",
  GET_ALL_VENDOR_DRIVERS = "GET_ALL_VENDOR_DRIVERS",
  GET_ALL_FREELANCE_DRIVERS = "GET_ALL_FREELANCE_DRIVERS",
  UPDATE_DRIVER_STATUS = "UPDATE_DRIVER_STATUS",
  UPDATE_DRIVER_APPROVAL = "UPDATE_DRIVER_APPROVAL",
  GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID",
  DELETE_DRIVER = "DELETE_DRIVER",
  GET_DRIVER_LOCATION = "GET_DRIVER_LOCATION",
}

export default DriversActionTypeEnum;
