enum EarningActionTypeEnum {
  GET_NET_EARNINGS_SUCCESS = "GET_NET_EARNINGS_SUCCESS",
  GET_NET_EARNINGS_FAILED = "GET_NET_EARNINGS_FAILED",
  GET_NET_EARNINGS_PENDING = "GET_NET_EARNINGS_PENDING",

  GET_CANCEL_ORDER_EARNING_SUCCESS = "GET_CANCEL_ORDER_EARNING_SUCCESS",
  GET_CANCEL_ORDER_EARNING_PENDING = "GET_CANCEL_ORDER_EARNING_PENDING",
  GET_CANCEL_ORDER_EARNING_FAILED = "GET_CANCEL_ORDER_EARNING_FAILED",
}

export default EarningActionTypeEnum;
