enum TimeSlotActionTypeEnum {
  TIME_SLOT_LOADING = "TIME_SLOT_LOADING",
  TIME_SLOT_LOADED = "TIME_SLOT_LOADED",
  GET_TIME_SLOT = "GET_TIME_SLOT",
  ADD_TIME_SLOT = "ADD_TIME_SLOT",
  EDIT_TIME_SLOT = "EDIT_TIME_SLOT",
  DELETE_TIME_SLOT = "DELETE_TIME_SLOT",
}

export default TimeSlotActionTypeEnum;
